# Generated by Django 3.1.4 on 2020-12-05 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
