# Generated by Django 3.0.8 on 2020-12-17 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201217_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
