# Generated by Django 3.0.8 on 2020-12-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201217_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_booking', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'v_booking',
                'managed': False,
            },
        ),
    ]
