# Generated by Django 3.0.8 on 2020-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookingview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'v_location',
                'managed': False,
            },
        ),
    ]
