# Generated by Django 3.0.8 on 2020-12-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cartview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'v_chart',
                'managed': False,
            },
        ),
    ]
