# Generated by Django 3.0.8 on 2020-12-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_viewchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
            ],
            options={
                'db_table': 'v_revenue',
                'managed': False,
            },
        ),
    ]
