# Generated by Django 3.0.8 on 2020-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_viewrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBooking',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_location', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phone_location', models.CharField(max_length=15)),
                ('address_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'v_detail',
                'managed': False,
            },
        ),
    ]
